// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `JoyStick.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____JoyStick_h__
#define ____JoyStick_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace RoboCompJoyStick
{

class JoyStick;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompJoyStick::JoyStick>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompJoyStick::JoyStick*);

}

}

namespace RoboCompJoyStick
{

class JoyStick;
bool operator==(const JoyStick&, const JoyStick&);
bool operator<(const JoyStick&, const JoyStick&);
::Ice::Object* upCast(::RoboCompJoyStick::JoyStick*);
typedef ::IceInternal::Handle< ::RoboCompJoyStick::JoyStick> JoyStickPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompJoyStick::JoyStick> JoyStickPrx;
void __patch(JoyStickPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompJoyStick
{

typedef ::std::vector< ::Ice::Byte> JoyStickBufferedData;

}

namespace RoboCompJoyStick
{

class Callback_JoyStick_readJoyStickBufferedData_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_JoyStick_readJoyStickBufferedData_Base> Callback_JoyStick_readJoyStickBufferedDataPtr;

class Callback_JoyStick_writeJoyStickBufferedData_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_JoyStick_writeJoyStickBufferedData_Base> Callback_JoyStick_writeJoyStickBufferedDataPtr;

}

namespace IceProxy
{

namespace RoboCompJoyStick
{

class JoyStick : virtual public ::IceProxy::Ice::Object
{
public:

    void readJoyStickBufferedData(::RoboCompJoyStick::JoyStickBufferedData& gbd)
    {
        readJoyStickBufferedData(gbd, 0);
    }
    void readJoyStickBufferedData(::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context& __ctx)
    {
        readJoyStickBufferedData(gbd, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_readJoyStickBufferedData(const ::IceInternal::Function<void (const ::RoboCompJoyStick::JoyStickBufferedData&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_readJoyStickBufferedData(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_readJoyStickBufferedData(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_readJoyStickBufferedData(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_readJoyStickBufferedData(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::RoboCompJoyStick::JoyStickBufferedData&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_readJoyStickBufferedData(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_readJoyStickBufferedData(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_readJoyStickBufferedData(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_readJoyStickBufferedData(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::RoboCompJoyStick::JoyStickBufferedData&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::RoboCompJoyStick::JoyStickBufferedData&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::RoboCompJoyStick::JoyStickPrx __proxy = ::RoboCompJoyStick::JoyStickPrx::uncheckedCast(__result->getProxy());
                ::RoboCompJoyStick::JoyStickBufferedData gbd;
                try
                {
                    __proxy->end_readJoyStickBufferedData(gbd, __result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(gbd);
                }
            }
        
        private:
            
            ::std::function<void (const ::RoboCompJoyStick::JoyStickBufferedData&)> _response;
        };
        return begin_readJoyStickBufferedData(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_readJoyStickBufferedData()
    {
        return begin_readJoyStickBufferedData(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_readJoyStickBufferedData(const ::Ice::Context& __ctx)
    {
        return begin_readJoyStickBufferedData(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_readJoyStickBufferedData(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_readJoyStickBufferedData(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_readJoyStickBufferedData(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_readJoyStickBufferedData(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_readJoyStickBufferedData(const ::RoboCompJoyStick::Callback_JoyStick_readJoyStickBufferedDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_readJoyStickBufferedData(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_readJoyStickBufferedData(const ::Ice::Context& __ctx, const ::RoboCompJoyStick::Callback_JoyStick_readJoyStickBufferedDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_readJoyStickBufferedData(&__ctx, __del, __cookie);
    }

    void end_readJoyStickBufferedData(::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::AsyncResultPtr&);
    
private:

    void readJoyStickBufferedData(::RoboCompJoyStick::JoyStickBufferedData&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_readJoyStickBufferedData(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd)
    {
        writeJoyStickBufferedData(gbd, 0);
    }
    void writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context& __ctx)
    {
        writeJoyStickBufferedData(gbd, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_writeJoyStickBufferedData(gbd, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_writeJoyStickBufferedData(gbd, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_writeJoyStickBufferedData(gbd, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_writeJoyStickBufferedData(gbd, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd)
    {
        return begin_writeJoyStickBufferedData(gbd, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context& __ctx)
    {
        return begin_writeJoyStickBufferedData(gbd, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_writeJoyStickBufferedData(gbd, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_writeJoyStickBufferedData(gbd, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::RoboCompJoyStick::Callback_JoyStick_writeJoyStickBufferedDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_writeJoyStickBufferedData(gbd, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context& __ctx, const ::RoboCompJoyStick::Callback_JoyStick_writeJoyStickBufferedDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_writeJoyStickBufferedData(gbd, &__ctx, __del, __cookie);
    }

    void end_writeJoyStickBufferedData(const ::Ice::AsyncResultPtr&);
    
private:

    void writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<JoyStick> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_secure(bool __secure) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_twoway() const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_oneway() const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_batchOneway() const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_datagram() const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_batchDatagram() const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_compress(bool __compress) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_timeout(int __timeout) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<JoyStick> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<JoyStick*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace RoboCompJoyStick
{

class JoyStick : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void readJoyStickBufferedData(::RoboCompJoyStick::JoyStickBufferedData&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace RoboCompJoyStick
{

class JoyStick : virtual public ::IceDelegate::RoboCompJoyStick::JoyStick,
                 virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void readJoyStickBufferedData(::RoboCompJoyStick::JoyStickBufferedData&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace RoboCompJoyStick
{

class JoyStick : virtual public ::IceDelegate::RoboCompJoyStick::JoyStick,
                 virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void readJoyStickBufferedData(::RoboCompJoyStick::JoyStickBufferedData&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace RoboCompJoyStick
{

class JoyStick : virtual public ::Ice::Object
{
public:

    typedef JoyStickPrx ProxyType;
    typedef JoyStickPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void readJoyStickBufferedData(::RoboCompJoyStick::JoyStickBufferedData&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___readJoyStickBufferedData(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___writeJoyStickBufferedData(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const JoyStick& l, const JoyStick& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const JoyStick& l, const JoyStick& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace RoboCompJoyStick
{

template<class T>
class CallbackNC_JoyStick_readJoyStickBufferedData : public Callback_JoyStick_readJoyStickBufferedData_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::RoboCompJoyStick::JoyStickBufferedData&);

    CallbackNC_JoyStick_readJoyStickBufferedData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompJoyStick::JoyStickPrx __proxy = ::RoboCompJoyStick::JoyStickPrx::uncheckedCast(__result->getProxy());
        ::RoboCompJoyStick::JoyStickBufferedData gbd;
        try
        {
            __proxy->end_readJoyStickBufferedData(gbd, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(gbd);
        }
    }

    Response response;
};

template<class T> Callback_JoyStick_readJoyStickBufferedDataPtr
newCallback_JoyStick_readJoyStickBufferedData(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::RoboCompJoyStick::JoyStickBufferedData&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JoyStick_readJoyStickBufferedData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_JoyStick_readJoyStickBufferedDataPtr
newCallback_JoyStick_readJoyStickBufferedData(T* instance, void (T::*cb)(const ::RoboCompJoyStick::JoyStickBufferedData&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JoyStick_readJoyStickBufferedData<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_JoyStick_readJoyStickBufferedData : public Callback_JoyStick_readJoyStickBufferedData_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::RoboCompJoyStick::JoyStickBufferedData&, const CT&);

    Callback_JoyStick_readJoyStickBufferedData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompJoyStick::JoyStickPrx __proxy = ::RoboCompJoyStick::JoyStickPrx::uncheckedCast(__result->getProxy());
        ::RoboCompJoyStick::JoyStickBufferedData gbd;
        try
        {
            __proxy->end_readJoyStickBufferedData(gbd, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(gbd, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_JoyStick_readJoyStickBufferedDataPtr
newCallback_JoyStick_readJoyStickBufferedData(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::RoboCompJoyStick::JoyStickBufferedData&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JoyStick_readJoyStickBufferedData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_JoyStick_readJoyStickBufferedDataPtr
newCallback_JoyStick_readJoyStickBufferedData(T* instance, void (T::*cb)(const ::RoboCompJoyStick::JoyStickBufferedData&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JoyStick_readJoyStickBufferedData<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_JoyStick_writeJoyStickBufferedData : public Callback_JoyStick_writeJoyStickBufferedData_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_JoyStick_writeJoyStickBufferedData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_JoyStick_writeJoyStickBufferedDataPtr
newCallback_JoyStick_writeJoyStickBufferedData(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JoyStick_writeJoyStickBufferedData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_JoyStick_writeJoyStickBufferedDataPtr
newCallback_JoyStick_writeJoyStickBufferedData(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JoyStick_writeJoyStickBufferedData<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_JoyStick_writeJoyStickBufferedDataPtr
newCallback_JoyStick_writeJoyStickBufferedData(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JoyStick_writeJoyStickBufferedData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_JoyStick_writeJoyStickBufferedDataPtr
newCallback_JoyStick_writeJoyStickBufferedData(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JoyStick_writeJoyStickBufferedData<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_JoyStick_writeJoyStickBufferedData : public Callback_JoyStick_writeJoyStickBufferedData_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_JoyStick_writeJoyStickBufferedData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_JoyStick_writeJoyStickBufferedDataPtr
newCallback_JoyStick_writeJoyStickBufferedData(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JoyStick_writeJoyStickBufferedData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_JoyStick_writeJoyStickBufferedDataPtr
newCallback_JoyStick_writeJoyStickBufferedData(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JoyStick_writeJoyStickBufferedData<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_JoyStick_writeJoyStickBufferedDataPtr
newCallback_JoyStick_writeJoyStickBufferedData(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JoyStick_writeJoyStickBufferedData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_JoyStick_writeJoyStickBufferedDataPtr
newCallback_JoyStick_writeJoyStickBufferedData(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JoyStick_writeJoyStickBufferedData<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
