// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `JoyStick.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <JoyStick.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompJoyStick__JoyStick__readJoyStickBufferedData_name = "readJoyStickBufferedData";

const ::std::string __RoboCompJoyStick__JoyStick__writeJoyStickBufferedData_name = "writeJoyStickBufferedData";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompJoyStick::upCast(::IceProxy::RoboCompJoyStick::JoyStick* p) { return p; }

void
::IceProxy::RoboCompJoyStick::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompJoyStick::JoyStick>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompJoyStick::JoyStick;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompJoyStick::JoyStick::readJoyStickBufferedData(::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompJoyStick__JoyStick__readJoyStickBufferedData_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompJoyStick__JoyStick__readJoyStickBufferedData_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompJoyStick::JoyStick* __del = dynamic_cast< ::IceDelegate::RoboCompJoyStick::JoyStick*>(__delBase.get());
            __del->readJoyStickBufferedData(gbd, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapperRelaxed(__delBase, __ex, true, __cnt, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompJoyStick::JoyStick::begin_readJoyStickBufferedData(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompJoyStick__JoyStick__readJoyStickBufferedData_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompJoyStick__JoyStick__readJoyStickBufferedData_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompJoyStick__JoyStick__readJoyStickBufferedData_name, ::Ice::Idempotent, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompJoyStick::JoyStick::end_readJoyStickBufferedData(::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompJoyStick__JoyStick__readJoyStickBufferedData_name);
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(gbd);
        __result->__endReadParams();
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

void
IceProxy::RoboCompJoyStick::JoyStick::writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompJoyStick__JoyStick__writeJoyStickBufferedData_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompJoyStick::JoyStick* __del = dynamic_cast< ::IceDelegate::RoboCompJoyStick::JoyStick*>(__delBase.get());
            __del->writeJoyStickBufferedData(gbd, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapperRelaxed(__delBase, __ex, true, __cnt, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompJoyStick::JoyStick::begin_writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompJoyStick__JoyStick__writeJoyStickBufferedData_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompJoyStick__JoyStick__writeJoyStickBufferedData_name, ::Ice::Idempotent, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(gbd);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompJoyStick::JoyStick::end_writeJoyStickBufferedData(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompJoyStick__JoyStick__writeJoyStickBufferedData_name);
}

const ::std::string&
IceProxy::RoboCompJoyStick::JoyStick::ice_staticId()
{
    return ::RoboCompJoyStick::JoyStick::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompJoyStick::JoyStick::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompJoyStick::JoyStick);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompJoyStick::JoyStick::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompJoyStick::JoyStick);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompJoyStick::JoyStick::__newInstance() const
{
    return new JoyStick;
}

void
IceDelegateM::RoboCompJoyStick::JoyStick::readJoyStickBufferedData(::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompJoyStick__JoyStick__readJoyStickBufferedData_name, ::Ice::Idempotent, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(gbd);
        __og.endReadParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::RoboCompJoyStick::JoyStick::writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompJoyStick__JoyStick__writeJoyStickBufferedData_name, ::Ice::Idempotent, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(gbd);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::RoboCompJoyStick::JoyStick::readJoyStickBufferedData(::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::RoboCompJoyStick::JoyStickBufferedData& __p_gbd, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_gbd(__p_gbd)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompJoyStick::JoyStick* servant = dynamic_cast< ::RoboCompJoyStick::JoyStick*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->readJoyStickBufferedData(_m_gbd, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::RoboCompJoyStick::JoyStickBufferedData& _m_gbd;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompJoyStick__JoyStick__readJoyStickBufferedData_name, ::Ice::Idempotent, __context);
    try
    {
        _DirectI __direct(gbd, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompJoyStick::JoyStick::writeJoyStickBufferedData(const ::RoboCompJoyStick::JoyStickBufferedData& gbd, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompJoyStick::JoyStickBufferedData& __p_gbd, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_gbd(__p_gbd)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompJoyStick::JoyStick* servant = dynamic_cast< ::RoboCompJoyStick::JoyStick*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->writeJoyStickBufferedData(_m_gbd, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompJoyStick::JoyStickBufferedData& _m_gbd;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompJoyStick__JoyStick__writeJoyStickBufferedData_name, ::Ice::Idempotent, __context);
    try
    {
        _DirectI __direct(gbd, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* RoboCompJoyStick::upCast(::RoboCompJoyStick::JoyStick* p) { return p; }

namespace
{
const ::std::string __RoboCompJoyStick__JoyStick_ids[2] =
{
    "::Ice::Object",
    "::RoboCompJoyStick::JoyStick"
};

}

bool
RoboCompJoyStick::JoyStick::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompJoyStick__JoyStick_ids, __RoboCompJoyStick__JoyStick_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompJoyStick::JoyStick::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompJoyStick__JoyStick_ids[0], &__RoboCompJoyStick__JoyStick_ids[2]);
}

const ::std::string&
RoboCompJoyStick::JoyStick::ice_id(const ::Ice::Current&) const
{
    return __RoboCompJoyStick__JoyStick_ids[1];
}

const ::std::string&
RoboCompJoyStick::JoyStick::ice_staticId()
{
    return __RoboCompJoyStick__JoyStick_ids[1];
}

::Ice::DispatchStatus
RoboCompJoyStick::JoyStick::___readJoyStickBufferedData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Idempotent, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompJoyStick::JoyStickBufferedData gbd;
    readJoyStickBufferedData(gbd, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(gbd);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompJoyStick::JoyStick::___writeJoyStickBufferedData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Idempotent, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompJoyStick::JoyStickBufferedData gbd;
    __is->read(gbd);
    __inS.endReadParams();
    writeJoyStickBufferedData(gbd, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompJoyStick__JoyStick_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "readJoyStickBufferedData",
    "writeJoyStickBufferedData"
};

}

::Ice::DispatchStatus
RoboCompJoyStick::JoyStick::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompJoyStick__JoyStick_all, __RoboCompJoyStick__JoyStick_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompJoyStick__JoyStick_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___readJoyStickBufferedData(in, current);
        }
        case 5:
        {
            return ___writeJoyStickBufferedData(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompJoyStick::JoyStick::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompJoyStick::JoyStick::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompJoyStick::__patch(JoyStickPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompJoyStick::JoyStickPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompJoyStick::JoyStick::ice_staticId(), v);
    }
}
